### PR TITLE
feat: do not force to use draft 4 of json schema

### PR DESCRIPTION
**Pull request by javi11**
- Allow the user to override the metaSchema
- Add typescript types

### CODE REVIEW

**Comment by amazing-gao** [comment]
Because of the specification v2.0.

> Primitive data types in the Swagger Specification are based on the types supported by the JSON-Schema Draft 4. Models are described using the Schema Object which is a subset of JSON Schema Draft 4.

Ref: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types

**Comment by javi11** [comment]
@BiteBit can be that valid also for draft 5 no? used on openapi3? i think will be better to the user of the lib to select which draft to use

**Comment by amazing-gao** [comment]
> @BiteBit can be that valid also for draft 5 no? used on openapi3? i think will be better to the user of the lib to select which draft to use

This is a good idea. We can add an option `metaSchema` for users to select which draft to use, and the default value is draft 4 no.
I'd love to add this function if you can give me a pull request for it.

**Comment by javi11** [comment]
Hey, i just added that and the .d.ts. Let me know what do you think?

**Comment by amazing-gao** [comment]
@javi11 LGTM. Thanks a lot. I will publish it now.

**Pull request merged**
